[opener]

# Video

vlc_open = [
  { run = 'vlc "$@"', orphan = true, desc = "Open (VLC) }
]

vlc_enqueue = [
  { run = 'vlc --playlist-enqueue "$@"', orphan = true, desc = "Enqueue (VLC)" }
]

# Audio

audacious_open = [
  { run = 'audacious "$@"', orphan = true, desc = "Open (Audacious)" }
]

audacious_enqueue = [
  { run = 'audacious --enqueue "$@"', orphan = true, desc = "Enqueue (Audacious)" }
]

# Images

imv_open = [
  { run = 'imv-wayland "$@"', orphan = true, desc = "Open (Imv)" }
]

imv_open_dir = [
  { run = 'imv-dir "$@"', orphan = true, desc = "Open (Imv) }
]

[open]

rules = [
  { mime = "video/*", use = ["vlc_enqueue", "vlc_open"] },
  { mime = "audio/*", use = ["audacious_open", "audacious_enqueue"] },
  { mime = "image/*", use = "imv_open" },
  { mime = "inode/directory", use = ["vlc_enqueue", "vlc_open", "audacious_enqueue", "audacious_open", "imv_open_dir"] }
]
